// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zootlckyvjwwpcbkcfnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvb3RsY2t5dmp3d3BjYmtjZm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjMzNzEsImV4cCI6MjA2NDQzOTM3MX0.MBY0D5XBC3cFuQR-xuhz2Er5H1UMJi7CsTMQFaAMpEw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);